XCODE_USER_TEMPLATES_DIR=~/Library/Developer/Xcode/Templates/File\ Templates
XCODE_USER_SNIPPETS_DIR=~/Library/Developer/Xcode/UserData/CodeSnippets

STORYBOARD_TEMPLATES_DIR=Storyboards
VIEWCODE_TEMPLATES_DIR=ViewCode

install_templates:
  mkdir -p $(XCODE_USER_TEMPLATES_DIR)

  rm -fR $(XCODE_USER_TEMPLATES_DIR)/$(STORYBOARD_TEMPLATES_DIR)
  cp -R $(STORYBOARD_TEMPLATES_DIR) $(XCODE_USER_TEMPLATES_DIR)

  rm -fR $(XCODE_USER_TEMPLATES_DIR)/$(VIEWCODE_TEMPLATES_DIR)
  cp -R $(VIEWCODE_TEMPLATES_DIR) $(XCODE_USER_TEMPLATES_DIR)

uninstall_templates:
  rm -fR $(XCODE_USER_TEMPLATES_DIR)/$(STORYBOARD_TEMPLATES_DIR)
  rm -fR $(XCODE_USER_TEMPLATES_DIR)/$(VIEWCODE_TEMPLATES_DIR)
